# Use postgres/example user/password credentials
# version: '3.9'

networks:
  default:
    external: true
    name: docker_default
services:

  db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: uptime
      POSTGRES_DB: uptime
    volumes:
      # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/tables_postgres.sql:/docker-entrypoint-initdb.d/tables_postgres.sql
      - ./volumes/postgres:/var/lib/postgresql/data
    # command: /usr/local/bin/custom-entrypoint.sh
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# volumes:
  # postgre_volume:
